---
kind: pipeline
name: cypress-applitools-drone-ci

steps:
  - name: testing
    image: cypress/browsers:node12.14.1-chrome85-ff81
    commands:
      - npm install
      - npx eyes-setup
      - npx cypress run --headless --browser=chrome
type:
trigger:
  branch:
    - master
