---
kind: pipeline
name: cypress-applitools-drone-ci

steps:
  - name: testing
    image: cypress/included:5.3.0
    commands:
      - npm install
      - npx eyes-setup
      - npx cypress run --headless --browser=chrome --parallel
type:
trigger:
  event:
    include:
    - pull_request
